[package]
name = "part2"
version = "0.1.0"
authors = ["David Lang <davidlang42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
itertools = "0.6.0"